# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

before_install:
  - tlmgr install index

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls(type = "examples")'
